name: rentease
description: RentEase Flutter App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # UI Packages
  smooth_page_indicator: ^1.2.1
  iconsax: ^0.0.8

  # Utilities
  intl: ^0.20.2
  http: ^1.6.0
  logger: ^2.7.0
  url_launcher: ^6.3.2
  pdf: 3.11.3
  image_picker: ^1.1.2
  printing: ^5.13.4
  external_path: ^2.2.0
  permission_handler: ^12.0.3
  google_maps_flutter: ^2.17.1
  dotted_border: ^3.1.0
  supabase_flutter: ^2.9.1
  geocoding: ^3.0.0
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/products/
    - assets/states/
    - assets/user/
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/properties/
    - assets/fonts/Cairo-Regular.ttf
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf